# Generated by Django 3.1 on 2020-08-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_cabina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabin',
            name='wifi_password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cabin',
            name='wifi_ssid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
