# Generated by Django 3.1 on 2020-08-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_cabina', '0002_auto_20200821_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='save_images',
            new_name='save_all',
        ),
    ]
