# Generated by Django 3.1 on 2020-10-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_cabina', '0004_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabin',
            name='language',
            field=models.CharField(default='en', max_length=5),
        ),
    ]
